// Copyright 2022 Pavel Glushkov (@pashutk)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define MATRIX_ROWS  8
#define MATRIX_COLS  6

#define USE_SERIAL
#define SOFT_SERIAL_PIN D2

#define TAPPING_TERM 200
#define TAPPING_TOGGLE 2
#define HOLD_ON_OTHER_KEY_PRESS

// #define AUTO_SHIFT_REPEAT
// #define AUTO_SHIFT_TIMEOUT 180
// #define NO_AUTO_SHIFT_SPECIAL
// #define NO_AUTO_SHIFT_NUMERIC
// #define NO_AUTO_SHIFT_SYMBOLS

// #define MK_KINETIC_SPEED
// #define MOUSEKEY_INITIAL_SPEED 240
// #define MOUSEKEY_BASE_SPEED 2400
// #define MOUSEKEY_DECELERATED_SPEED 400
// #define MOUSEKEY_ACCELERATED_SPEED 1500
// #define MOUSEKEY_MOVE_DELTA 18

#define MOUSEKEY_INERTIA
#define MOUSEKEY_DELAY 0
#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_TIME_TO_MAX 60
#define MOUSEKEY_MAX_SPEED 32
#define MOUSEKEY_FRICTION  20
#define MOUSEKEY_MOVE_DELTA 1

#define COMBO_TERM 50
#define COMBO_STRICT_TIMER
#define COMBO_MUST_HOLD_MODS
#define COMBO_HOLD_TERM 165